import '../styles/globals.css'
import type { AppProps } from 'next/app'
import myStore from '../redux/store/store'
import Head from "next/head";
import { ConfigProvider } from 'antd';
import 'antd/dist/antd.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ConfigProvider direction="ltr">
      <Head>
        <title>CryptoList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ConfigProvider>
  );
}

export default myStore.withRedux(MyApp);
