import '../styles/globals.css'
import type { AppProps } from 'next/app'
// import { Provider } from 'react-redux'
import myStore from '../redux/store/store'
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    // <Provider store={myStore()}>
    <>
      <Head>
        <title>CryptoList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
    // </Provider>
  );
}

export default myStore.withRedux(MyApp);
